apiVersion: v1
kind: Service
metadata:
  name: publish-website
spec:
  selector:
    app: nginx-web
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30003
    protocol: TCP

